/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CinoRouteImport } from './routes/cino'
import { Route as MugenRouteImport } from './routes/mugen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CinoRoute = CinoRouteImport.update({
  id: '/cino',
  path: '/cino',
  getParentRoute: () => rootRouteImport,
} as any)
const MugenRoute = MugenRouteImport.update({
  id: '/mugen',
  path: '/mugen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cino': typeof CinoRoute
  '/mugen': typeof MugenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cino': typeof CinoRoute
  '/mugen': typeof MugenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cino': typeof CinoRoute
  '/mugen': typeof MugenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cino' | '/mugen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cino' | '/mugen'
  id: '__root__' | '/' | '/cino' | '/mugen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CinoRoute: typeof CinoRoute
  MugenRoute: typeof MugenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cino': {
      id: '/cino'
      path: '/cino'
      fullPath: '/cino'
      preLoaderRoute: typeof CinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mugen': {
      id: '/mugen'
      path: '/mugen'
      fullPath: '/mugen'
      preLoaderRoute: typeof MugenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CinoRoute: CinoRoute,
  MugenRoute: MugenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
